apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev
type: Opaque
stringData:
  # App variables
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: appdb

  # Postgres image REQUIRED variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: appdb
